//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./message_types');
//HELPER FUNCTIONS AND STRUCTURES

RpcMsg.RpcMessage_ping_args = function(args) {
};
RpcMsg.RpcMessage_ping_args.prototype = {};
RpcMsg.RpcMessage_ping_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RpcMsg.RpcMessage_ping_args.prototype.write = function(output) {
  output.writeStructBegin('RpcMessage_ping_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

RpcMsg.RpcMessage_ping_result = function(args) {
};
RpcMsg.RpcMessage_ping_result.prototype = {};
RpcMsg.RpcMessage_ping_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RpcMsg.RpcMessage_ping_result.prototype.write = function(output) {
  output.writeStructBegin('RpcMessage_ping_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

RpcMsg.RpcMessage_clientMsg_args = function(args) {
  this.msg = null;
  if (args) {
    if (args.msg !== undefined) {
      this.msg = args.msg;
    }
  }
};
RpcMsg.RpcMessage_clientMsg_args.prototype = {};
RpcMsg.RpcMessage_clientMsg_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.msg = new ttypes.Message();
        this.msg.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RpcMsg.RpcMessage_clientMsg_args.prototype.write = function(output) {
  output.writeStructBegin('RpcMessage_clientMsg_args');
  if (this.msg !== null && this.msg !== undefined) {
    output.writeFieldBegin('msg', Thrift.Type.STRUCT, 1);
    this.msg.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

RpcMsg.RpcMessage_clientMsg_result = function(args) {
  this.success = null;
  this.unavailable = null;
  if (args instanceof ttypes.PtyUnavailable) {
    this.unavailable = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.unavailable !== undefined) {
      this.unavailable = args.unavailable;
    }
  }
};
RpcMsg.RpcMessage_clientMsg_result.prototype = {};
RpcMsg.RpcMessage_clientMsg_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.unavailable = new ttypes.PtyUnavailable();
        this.unavailable.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RpcMsg.RpcMessage_clientMsg_result.prototype.write = function(output) {
  output.writeStructBegin('RpcMessage_clientMsg_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  if (this.unavailable !== null && this.unavailable !== undefined) {
    output.writeFieldBegin('unavailable', Thrift.Type.STRUCT, 1);
    this.unavailable.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

RpcMsg.RpcMessage_srvrMsg_args = function(args) {
  this.msg = null;
  if (args) {
    if (args.msg !== undefined) {
      this.msg = args.msg;
    }
  }
};
RpcMsg.RpcMessage_srvrMsg_args.prototype = {};
RpcMsg.RpcMessage_srvrMsg_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.msg = new ttypes.Message();
        this.msg.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RpcMsg.RpcMessage_srvrMsg_args.prototype.write = function(output) {
  output.writeStructBegin('RpcMessage_srvrMsg_args');
  if (this.msg !== null && this.msg !== undefined) {
    output.writeFieldBegin('msg', Thrift.Type.STRUCT, 1);
    this.msg.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

RpcMsg.RpcMessage_srvrMsg_result = function(args) {
  this.success = null;
  this.unavailable = null;
  if (args instanceof ttypes.PtyUnavailable) {
    this.unavailable = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.unavailable !== undefined) {
      this.unavailable = args.unavailable;
    }
  }
};
RpcMsg.RpcMessage_srvrMsg_result.prototype = {};
RpcMsg.RpcMessage_srvrMsg_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.unavailable = new ttypes.PtyUnavailable();
        this.unavailable.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RpcMsg.RpcMessage_srvrMsg_result.prototype.write = function(output) {
  output.writeStructBegin('RpcMessage_srvrMsg_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  if (this.unavailable !== null && this.unavailable !== undefined) {
    output.writeFieldBegin('unavailable', Thrift.Type.STRUCT, 1);
    this.unavailable.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

RpcMsg.RpcMessage_zip_args = function(args) {
};
RpcMsg.RpcMessage_zip_args.prototype = {};
RpcMsg.RpcMessage_zip_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RpcMsg.RpcMessage_zip_args.prototype.write = function(output) {
  output.writeStructBegin('RpcMessage_zip_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

RpcMsg.RpcMessage_zip_result = function(args) {
};
RpcMsg.RpcMessage_zip_result.prototype = {};
RpcMsg.RpcMessage_zip_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RpcMsg.RpcMessage_zip_result.prototype.write = function(output) {
  output.writeStructBegin('RpcMessage_zip_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

RpcMsg.RpcMessageClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
RpcMsg.RpcMessageClient.prototype = {};
RpcMsg.RpcMessageClient.prototype.seqid = function() { return this._seqid; }
RpcMsg.RpcMessageClient.prototype.new_seqid = function() { return this._seqid += 1; }
RpcMsg.RpcMessageClient.prototype.ping = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_ping();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_ping();
  }
};

RpcMsg.RpcMessageClient.prototype.send_ping = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('ping', Thrift.MessageType.CALL, this.seqid());
  var args = new RpcMsg.RpcMessage_ping_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

RpcMsg.RpcMessageClient.prototype.recv_ping = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new RpcMsg.RpcMessage_ping_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
RpcMsg.RpcMessageClient.prototype.clientMsg = function(msg, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_clientMsg(msg);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_clientMsg(msg);
  }
};

RpcMsg.RpcMessageClient.prototype.send_clientMsg = function(msg) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('clientMsg', Thrift.MessageType.CALL, this.seqid());
  var args = new RpcMsg.RpcMessage_clientMsg_args();
  args.msg = msg;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

RpcMsg.RpcMessageClient.prototype.recv_clientMsg = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new RpcMsg.RpcMessage_clientMsg_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.unavailable) {
    return callback(result.unavailable);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('clientMsg failed: unknown result');
};
RpcMsg.RpcMessageClient.prototype.srvrMsg = function(msg, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_srvrMsg(msg);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_srvrMsg(msg);
  }
};

RpcMsg.RpcMessageClient.prototype.send_srvrMsg = function(msg) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('srvrMsg', Thrift.MessageType.CALL, this.seqid());
  var args = new RpcMsg.RpcMessage_srvrMsg_args();
  args.msg = msg;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

RpcMsg.RpcMessageClient.prototype.recv_srvrMsg = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new RpcMsg.RpcMessage_srvrMsg_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.unavailable) {
    return callback(result.unavailable);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('srvrMsg failed: unknown result');
};
RpcMsg.RpcMessageClient.prototype.zip = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_zip();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_zip();
  }
};

RpcMsg.RpcMessageClient.prototype.send_zip = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('zip', Thrift.MessageType.ONEWAY, this.seqid());
  var args = new RpcMsg.RpcMessage_zip_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};
RpcMsg.RpcMessageProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
RpcMsg.RpcMessageProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

RpcMsg.RpcMessageProcessor.prototype.process_ping = function(seqid, input, output) {
  var args = new RpcMsg.RpcMessage_ping_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.ping.length === 0) {
    Q.fcall(this._handler.ping)
      .then(function(result) {
        var result = new RpcMsg.RpcMessage_ping_result({success: result});
        output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new RpcMsg.RpcMessage_ping_result(err);
        output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.ping( function (err, result) {
      var result = new RpcMsg.RpcMessage_ping_result((err != null ? err : {success: result}));
      output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

RpcMsg.RpcMessageProcessor.prototype.process_clientMsg = function(seqid, input, output) {
  var args = new RpcMsg.RpcMessage_clientMsg_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.clientMsg.length === 1) {
    Q.fcall(this._handler.clientMsg, args.msg)
      .then(function(result) {
        var result = new RpcMsg.RpcMessage_clientMsg_result({success: result});
        output.writeMessageBegin("clientMsg", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new RpcMsg.RpcMessage_clientMsg_result(err);
        output.writeMessageBegin("clientMsg", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.clientMsg(args.msg,  function (err, result) {
      var result = new RpcMsg.RpcMessage_clientMsg_result((err != null ? err : {success: result}));
      output.writeMessageBegin("clientMsg", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

RpcMsg.RpcMessageProcessor.prototype.process_srvrMsg = function(seqid, input, output) {
  var args = new RpcMsg.RpcMessage_srvrMsg_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.srvrMsg.length === 1) {
    Q.fcall(this._handler.srvrMsg, args.msg)
      .then(function(result) {
        var result = new RpcMsg.RpcMessage_srvrMsg_result({success: result});
        output.writeMessageBegin("srvrMsg", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new RpcMsg.RpcMessage_srvrMsg_result(err);
        output.writeMessageBegin("srvrMsg", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.srvrMsg(args.msg,  function (err, result) {
      var result = new RpcMsg.RpcMessage_srvrMsg_result((err != null ? err : {success: result}));
      output.writeMessageBegin("srvrMsg", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

RpcMsg.RpcMessageProcessor.prototype.process_zip = function(seqid, input, output) {
  var args = new RpcMsg.RpcMessage_zip_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.zip()
}

